# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Python_Belt', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likecount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
