# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Python_Belt', '0005_auto_20190624_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likedby',
            field=models.CommaSeparatedIntegerField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
